=== ShawnLobo20/Chattel-Collection/CIA1/emply.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/emply" 
xmlns:tns="http://www.example.org/emply" 
elementFormDefault="qualified">

<complexType name="Company">
<sequence>
<element name="Employee" type="tns:EmployeeType" minOccurs="1" maxOccurs="2">
</element>
</sequence>
</complexType>

<complexType name="EmployeeType">
<sequence>
<element name="Emp-name" type="string"></element>
<element name="Emp-age" type="integer"></element>
<element name="Emp-salary" type="tns:MyEmployee"></element>
<element name="Emp-emailid" type="string"></element>
<element name="Emp-Phonenum" type="integer"></element>
<element name="Emp-designation" type="string"></element>
</sequence>
<attribute name="emid" type="ID" use="required"></attribute>
</complexType>

<element name="globalEmployee" type="tns:Company"></element>

<simpleType name="MyEmployee">
<restriction base="integer">
<minExclusive value="49000"></minExclusive>
<maxExclusive value="200001"></maxExclusive>
</restriction>
</simpleType>


</schema>

=== ShawnLobo20/Chattel-Collection/CIA1/emp1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalEmployee xmlns:tns="http://www.example.org/emply" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/emply emply.xsd ">
  <tns:Employee emid="em1">
    <tns:Emp-name>John</tns:Emp-name>
    <tns:Emp-age>27</tns:Emp-age>
    <tns:Emp-salary>200000</tns:Emp-salary>
    <tns:Emp-emailid>john@gmail.com</tns:Emp-emailid>
    <tns:Emp-Phonenum>1234567897</tns:Emp-Phonenum>
    <tns:Emp-designation>HOD</tns:Emp-designation>
  </tns:Employee>
  
  <tns:Employee emid="em2">
    <tns:Emp-name>Ron</tns:Emp-name>
    <tns:Emp-age>22</tns:Emp-age>
    <tns:Emp-salary>56000</tns:Emp-salary>
    <tns:Emp-emailid>ron@gmail.com</tns:Emp-emailid>
    <tns:Emp-Phonenum>789456123</tns:Emp-Phonenum>
    <tns:Emp-designation>Manager</tns:Emp-designation>
  </tns:Employee>
</tns:globalEmployee>
